/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemaponto.view;

import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Lenovo
 */
public class ViewBaterPonto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewBaterPonto.class.getName());
    private DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
    
    /**
     * Creates new form ViewBaterPonto
     */
    public ViewBaterPonto() {
        initComponents();
    }
    
    public void setLabels(String nomeFuncionario){
        //Método para puxar o nome do funcionario + data atual para o registro do ponto
        Timer timer = new Timer(1000, e -> {
        LocalDateTime dataAtual = LocalDateTime.now();
            lbDataHoje.setText(dataAtual.format(formato));
        });
        
        timer.start();
        
        lbNomeFuncionario.setText(nomeFuncionario);
    }
    
    public void atualizaRegistros(String registro){
        txtRegistroPonto.setText(registro); 
    }
    
    public String getDataAtual(){
        LocalDateTime dataAtual = LocalDateTime.now();
        return dataAtual.format(formato);
    }
    
    public void mostrarTela(){
        setVisible(true);
    }
    
    public void adicionarAcaoBtnEntradaPonto(ActionListener a){
        btnEntrada.addActionListener(a);
    }
    
    public void adicionarAcaoBtnSaidaPonto(ActionListener a){
        btnSaida.addActionListener(a);
    }
    
    public JButton getBtnSaida(){
        return btnSaida;
    }
    
    public JButton getBtnEntrada(){
        return btnEntrada;
    }
    
    public String getRegistrosPonto(){
        return txtRegistroPonto.getText();
    }
    
    public void apresentaMensagem(String msg) {  
        JOptionPane.showMessageDialog(null, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeFuncionario = new javax.swing.JLabel();
        lbDataHoje = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRegistroPonto = new javax.swing.JTextArea();
        btnEntrada = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNomeFuncionario.setText("NomeFuncionario");

        lbDataHoje.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbDataHoje.setText("Hora do Dia");

        txtRegistroPonto.setColumns(20);
        txtRegistroPonto.setRows(5);
        jScrollPane2.setViewportView(txtRegistroPonto);

        btnEntrada.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEntrada.setText("Entrada");

        btnSaida.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnSaida.setText("Saida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbNomeFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDataHoje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDataHoje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrada)
                    .addComponent(btnSaida))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnSaida;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbDataHoje;
    private javax.swing.JLabel lbNomeFuncionario;
    private javax.swing.JTextArea txtRegistroPonto;
    // End of variables declaration//GEN-END:variables
}
