/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemaponto.view;

import br.com.sistemaponto.Main;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 * @author Rafael
 * @since 09/06/2026
 */
public class ViewMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewMenu.class.getName());

    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
        lbVersao.setText(Main.versao);
    }
    
    public void apresentarTela(){
        setVisible(true);
    }
    
    public void apresentaMensagem(String msg) {  
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public void adcionarAcaoBtnManterFuncionario(ActionListener a){
        btnManterFuncionario.addActionListener(a);
    }
    
    public void adcionarAcaoBtnBaterPonto(ActionListener a){
        btnBaterPonto.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        btnManterFuncionario = new javax.swing.JButton();
        btnBaterPonto = new javax.swing.JButton();
        lbVersao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setText("Sistema Ponto - Menu Inicial");

        btnManterFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManterFuncionario.setText("Cadastro");

        btnBaterPonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBaterPonto.setText("Bater Ponto");

        lbVersao.setText("Versao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManterFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaterPonto, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbTitulo)
                .addGap(39, 39, 39)
                .addComponent(btnManterFuncionario)
                .addGap(18, 18, 18)
                .addComponent(btnBaterPonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lbVersao))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaterPonto;
    private javax.swing.JButton btnManterFuncionario;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbVersao;
    // End of variables declaration//GEN-END:variables
}
